"""
Registros curados del dataset del tutor de matemáticas.

Cada registro es la unidad mínima del corpus. La salida textual NO se escribe
a mano: se construye mecánicamente a partir de `pasos` + `respuesta_final` en
`dataset_fuente.py`. Así el formato uniforme queda garantizado por construcción
y no depende de la disciplina del anotador.

Campos
------
id              : identificador estable (prefijo de categoría + consecutivo).
categoria       : una de las 11 clases del esquema de etiquetado.
tipo            : "problema" (lenguaje natural) | "operacion" (expresión directa).
nivel           : "basico" | "intermedio".
origen          : "base"  -> proviene de los 50 ejemplos originales (normalizado).
                  "nuevo" -> añadido durante la curación para balancear clases.
entrada         : lo que escribe el estudiante.
pasos           : lista de pasos del procedimiento (1 a 4).
respuesta_final : respuesta legible para humanos, puede incluir unidades.
valor           : forma canónica usada por las métricas automáticas
                  (número o fracción "a/b", sin unidades ni texto).
check           : expresión Python opcional; el validador comprueba que su
                  resultado coincide con `valor`. Es la red de seguridad contra
                  errores aritméticos en el corpus.
"""


def R(id, categoria, tipo, nivel, origen, entrada, pasos,
      respuesta_final, valor, check=None):
    return {
        "id": id,
        "categoria": categoria,
        "tipo": tipo,
        "nivel": nivel,
        "origen": origen,
        "entrada": entrada,
        "pasos": pasos,
        "respuesta_final": respuesta_final,
        "valor": valor,
        "check": check,
    }


REGISTROS = []

# ---------------------------------------------------------------- suma (15)
REGISTROS += [
    R("sum-01", "suma", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 245 + 378.",
      ["Sumamos unidades, decenas y centenas alineando las cifras.",
       "245 + 378 = 623."],
      "623", "623", "245+378"),
    R("sum-02", "suma", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 3.75 + 2.48.",
      ["Alineamos la coma decimal antes de sumar.",
       "3.75 + 2.48 = 6.23."],
      "6.23", "6.23", "3.75+2.48"),
    R("sum-03", "suma", "problema", "basico", "base",
      "Juan recorrió 3.5 kilómetros por la mañana y 2.8 kilómetros por la tarde. ¿Cuántos kilómetros recorrió en total?",
      ["El total es la suma de las dos distancias.",
       "3.5 + 2.8 = 6.3."],
      "6.3 kilómetros", "6.3", "3.5+2.8"),
    R("sum-04", "suma", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 1250 + 3480.",
      ["Sumamos los dos números.",
       "1250 + 3480 = 4730."],
      "4730", "4730", "1250+3480"),
    R("sum-05", "suma", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 0.75 + 0.6.",
      ["Escribimos 0.6 como 0.60 para igualar los decimales.",
       "0.75 + 0.60 = 1.35."],
      "1.35", "1.35", "0.75+0.6"),
    R("sum-06", "suma", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 12 + 25 + 38.",
      ["Sumamos los dos primeros: 12 + 25 = 37.",
       "Sumamos el tercero: 37 + 38 = 75."],
      "75", "75", "12+25+38"),
    R("sum-07", "suma", "problema", "basico", "nuevo",
      "Una biblioteca tenía 145 libros y recibió 89 libros nuevos. ¿Cuántos libros tiene ahora?",
      ["Al recibir libros nuevos el total aumenta, así que sumamos.",
       "145 + 89 = 234."],
      "234 libros", "234", "145+89"),
    R("sum-08", "suma", "problema", "basico", "nuevo",
      "Camila ahorró 15000 pesos el lunes y 22500 pesos el martes. ¿Cuánto ahorró en total?",
      ["El ahorro total es la suma de los dos días.",
       "15000 + 22500 = 37500."],
      "37500 pesos", "37500", "15000+22500"),
    R("sum-09", "suma", "problema", "basico", "nuevo",
      "A un estadio entraron 1850 adultos y 2340 niños. ¿Cuántas personas entraron en total?",
      ["Juntamos los dos grupos de personas.",
       "1850 + 2340 = 4190."],
      "4190 personas", "4190", "1850+2340"),
    R("sum-10", "suma", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 4096 + 928.",
      ["Sumamos los dos números.",
       "4096 + 928 = 5024."],
      "5024", "5024", "4096+928"),
    R("sum-11", "suma", "problema", "basico", "nuevo",
      "Una ruta de senderismo tiene un primer tramo de 2.25 kilómetros y un segundo tramo de 3.75 kilómetros. ¿Cuál es la longitud total de la ruta?",
      ["Sumamos la longitud de los dos tramos.",
       "2.25 + 3.75 = 6."],
      "6 kilómetros", "6", "2.25+3.75"),
    R("sum-12", "suma", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 18.9 + 7.05.",
      ["Escribimos 18.9 como 18.90 para igualar los decimales.",
       "18.90 + 7.05 = 25.95."],
      "25.95", "25.95", "18.9+7.05"),
    R("sum-13", "suma", "problema", "basico", "nuevo",
      "Una tienda vendió 47 camisetas el sábado y 63 el domingo. ¿Cuántas camisetas vendió durante el fin de semana?",
      ["Sumamos las ventas de los dos días.",
       "47 + 63 = 110."],
      "110 camisetas", "110", "47+63"),
    R("sum-14", "suma", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 7845 + 2155.",
      ["Sumamos los dos números.",
       "7845 + 2155 = 10000."],
      "10000", "10000", "7845+2155"),
    R("sum-15", "suma", "problema", "basico", "nuevo",
      "En una bodega hay tres cajas de manzanas con 120, 95 y 60 unidades. ¿Cuántas manzanas hay en total?",
      ["Sumamos las dos primeras cajas: 120 + 95 = 215.",
       "Sumamos la tercera caja: 215 + 60 = 275."],
      "275 manzanas", "275", "120+95+60"),
]

# --------------------------------------------------------------- resta (15)
REGISTROS += [
    R("res-01", "resta", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 812 - 459.",
      ["Restamos alineando las cifras y pidiendo prestado donde haga falta.",
       "812 - 459 = 353."],
      "353", "353", "812-459"),
    R("res-02", "resta", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 8.4 - 3.27.",
      ["Escribimos 8.4 como 8.40 para igualar los decimales.",
       "8.40 - 3.27 = 5.13."],
      "5.13", "5.13", "8.4-3.27"),
    R("res-03", "resta", "problema", "intermedio", "base",
      "La temperatura era de 6 grados Celsius por la mañana y descendió 9 grados durante la noche. ¿Cuál fue la temperatura final?",
      ["Un descenso se representa restando.",
       "6 - 9 = -3, es decir, tres grados bajo cero."],
      "-3 grados Celsius", "-3", "6-9"),
    R("res-04", "resta", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 5000 - 1275.",
      ["Restamos los dos números.",
       "5000 - 1275 = 3725."],
      "3725", "3725", "5000-1275"),
    R("res-05", "resta", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 100 - 37.5.",
      ["Escribimos 100 como 100.0 para igualar los decimales.",
       "100.0 - 37.5 = 62.5."],
      "62.5", "62.5", "100-37.5"),
    R("res-06", "resta", "problema", "basico", "nuevo",
      "Una biblioteca tiene 320 libros y presta 145. ¿Cuántos libros quedan disponibles?",
      ["Los libros prestados se descuentan del total.",
       "320 - 145 = 175."],
      "175 libros", "175", "320-145"),
    R("res-07", "resta", "problema", "basico", "nuevo",
      "Un tanque contiene 250 litros de agua y se utilizan 88 litros. ¿Cuántos litros quedan?",
      ["Restamos el agua utilizada al contenido inicial.",
       "250 - 88 = 162."],
      "162 litros", "162", "250-88"),
    R("res-08", "resta", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 10000 - 6375.",
      ["Restamos los dos números.",
       "10000 - 6375 = 3625."],
      "3625", "3625", "10000-6375"),
    R("res-09", "resta", "problema", "basico", "nuevo",
      "Andrés tenía 45000 pesos y gastó 28500 pesos. ¿Cuánto dinero le queda?",
      ["Al gasto lo restamos del dinero inicial.",
       "45000 - 28500 = 16500."],
      "16500 pesos", "16500", "45000-28500"),
    R("res-10", "resta", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 7.2 - 0.85.",
      ["Escribimos 7.2 como 7.20 para igualar los decimales.",
       "7.20 - 0.85 = 6.35."],
      "6.35", "6.35", "7.2-0.85"),
    R("res-11", "resta", "problema", "intermedio", "nuevo",
      "Sofía mide 1.68 metros y su hermano mide 1.52 metros. ¿Cuál es la diferencia de estatura entre ellos?",
      ["La diferencia se obtiene restando la estatura menor a la mayor.",
       "1.68 - 1.52 = 0.16."],
      "0.16 metros", "0.16", "1.68-1.52"),
    R("res-12", "resta", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 604 - 78.",
      ["Restamos los dos números.",
       "604 - 78 = 526."],
      "526", "526", "604-78"),
    R("res-13", "resta", "problema", "basico", "nuevo",
      "Un teatro tiene 500 asientos y 372 están ocupados. ¿Cuántos asientos quedan libres?",
      ["Restamos los asientos ocupados al total.",
       "500 - 372 = 128."],
      "128 asientos", "128", "500-372"),
    R("res-14", "resta", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: -5 - 12.",
      ["Partimos de -5 y retrocedemos 12 unidades en la recta numérica.",
       "-5 - 12 = -17."],
      "-17", "-17", "-5-12"),
    R("res-15", "resta", "problema", "intermedio", "nuevo",
      "En Bogotá la temperatura es de 14 grados Celsius y en el Nevado del Ruiz es de -3 grados Celsius. ¿Cuál es la diferencia de temperatura?",
      ["La diferencia es la temperatura mayor menos la menor.",
       "14 - (-3) = 14 + 3 = 17."],
      "17 grados Celsius", "17", "14-(-3)"),
]

# ------------------------------------------------------- multiplicacion (15)
REGISTROS += [
    R("mul-01", "multiplicacion", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 36 × 24.",
      ["Descomponemos: 36 × 24 = 36 × 20 + 36 × 4.",
       "720 + 144 = 864."],
      "864", "864", "36*24"),
    R("mul-02", "multiplicacion", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 6.5 × 1.2.",
      ["Multiplicamos como si no hubiera comas: 65 × 12 = 780.",
       "El resultado tiene dos cifras decimales: 7.80 = 7.8."],
      "7.8", "7.8", "6.5*1.2"),
    R("mul-03", "multiplicacion", "problema", "intermedio", "base",
      "Un automóvil viaja a una velocidad constante de 72 kilómetros por hora. ¿Cuántos kilómetros recorrerá en 2 horas y 30 minutos?",
      ["Convertimos el tiempo a horas: 2 horas y 30 minutos = 2.5 horas.",
       "Distancia = velocidad × tiempo = 72 × 2.5 = 180."],
      "180 kilómetros", "180", "72*2.5"),
    R("mul-04", "multiplicacion", "problema", "basico", "base",
      "Pedro ahorra 12000 pesos cada semana. ¿Cuánto dinero habrá ahorrado después de 8 semanas?",
      ["Repetir el mismo ahorro varias veces es multiplicar.",
       "12000 × 8 = 96000."],
      "96000 pesos", "96000", "12000*8"),
    R("mul-05", "multiplicacion", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 125 × 8.",
      ["Multiplicamos los dos números.",
       "125 × 8 = 1000."],
      "1000", "1000", "125*8"),
    R("mul-06", "multiplicacion", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 47 × 30.",
      ["Multiplicamos 47 × 3 = 141 y añadimos un cero.",
       "47 × 30 = 1410."],
      "1410", "1410", "47*30"),
    R("mul-07", "multiplicacion", "problema", "basico", "nuevo",
      "Un almacén recibe 15 cajas y cada caja trae 24 lápices. ¿Cuántos lápices recibió?",
      ["Multiplicamos el número de cajas por los lápices de cada una.",
       "15 × 24 = 360."],
      "360 lápices", "360", "15*24"),
    R("mul-08", "multiplicacion", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 2.5 × 4.4.",
      ["Multiplicamos sin comas: 25 × 44 = 1100.",
       "El resultado tiene dos cifras decimales: 11.00 = 11."],
      "11", "11", "2.5*4.4"),
    R("mul-09", "multiplicacion", "problema", "basico", "nuevo",
      "La entrada a un museo cuesta 8500 pesos por persona. ¿Cuánto pagan 6 personas?",
      ["Multiplicamos el precio por el número de personas.",
       "8500 × 6 = 51000."],
      "51000 pesos", "51000", "8500*6"),
    R("mul-10", "multiplicacion", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 105 × 12.",
      ["Descomponemos: 105 × 12 = 105 × 10 + 105 × 2.",
       "1050 + 210 = 1260."],
      "1260", "1260", "105*12"),
    R("mul-11", "multiplicacion", "problema", "basico", "nuevo",
      "Un auditorio tiene 7 filas y cada fila tiene 18 sillas. ¿Cuántas sillas hay en total?",
      ["Multiplicamos el número de filas por las sillas de cada fila.",
       "7 × 18 = 126."],
      "126 sillas", "126", "7*18"),
    R("mul-12", "multiplicacion", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 0.25 × 64.",
      ["0.25 equivale a un cuarto, así que dividimos 64 entre 4.",
       "0.25 × 64 = 16."],
      "16", "16", "0.25*64"),
    R("mul-13", "multiplicacion", "problema", "intermedio", "nuevo",
      "Un bus escolar recorre 85 kilómetros cada día. ¿Cuántos kilómetros recorre en 14 días?",
      ["Multiplicamos el recorrido diario por el número de días.",
       "85 × 14 = 1190."],
      "1190 kilómetros", "1190", "85*14"),
    R("mul-14", "multiplicacion", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 340 × 25.",
      ["Descomponemos: 340 × 25 = 340 × 20 + 340 × 5.",
       "6800 + 1700 = 8500."],
      "8500", "8500", "340*25"),
    R("mul-15", "multiplicacion", "problema", "intermedio", "nuevo",
      "Una tienda vende 9 bolsas de arroz de 2.5 kilogramos cada una. ¿Cuántos kilogramos vendió?",
      ["Multiplicamos el número de bolsas por el peso de cada una.",
       "9 × 2.5 = 22.5."],
      "22.5 kilogramos", "22.5", "9*2.5"),
]

# ------------------------------------------------------------ division (15)
REGISTROS += [
    R("div-01", "division", "problema", "basico", "base",
      "María tiene 48 caramelos y quiere repartirlos por igual entre 6 amigos. ¿Cuántos caramelos recibirá cada amigo?",
      ["Repartir en partes iguales es dividir.",
       "48 ÷ 6 = 8."],
      "8 caramelos", "8", "48/6"),
    R("div-02", "division", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 864 ÷ 12.",
      ["Dividimos los dos números.",
       "864 ÷ 12 = 72."],
      "72", "72", "864/12"),
    R("div-03", "division", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 15.6 ÷ 0.4.",
      ["Multiplicamos ambos por 10 para quitar el decimal del divisor: 156 ÷ 4.",
       "156 ÷ 4 = 39."],
      "39", "39", "15.6/0.4"),
    R("div-04", "division", "problema", "intermedio", "base",
      "Un colegio organiza una excursión para 96 estudiantes. Cada bus tiene capacidad para 28 estudiantes. ¿Cuántos buses se necesitan para transportar a todos?",
      ["Dividimos: 96 ÷ 28 = 3.43 aproximadamente.",
       "No se puede usar una fracción de bus, así que redondeamos hacia arriba: 4 buses."],
      "4 buses", "4", "-(-96//28)"),
    R("div-05", "division", "problema", "basico", "base",
      "Pedro ahorra 12000 pesos cada semana y desea reunir 120000 pesos. ¿Cuántas semanas necesita?",
      ["Dividimos la meta entre el ahorro semanal.",
       "120000 ÷ 12000 = 10."],
      "10 semanas", "10", "120000/12000"),
    R("div-06", "division", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 1000 ÷ 25.",
      ["Dividimos los dos números.",
       "1000 ÷ 25 = 40."],
      "40", "40", "1000/25"),
    R("div-07", "division", "problema", "basico", "nuevo",
      "En un colegio hay 156 estudiantes que se reparten en 4 grupos iguales. ¿Cuántos estudiantes quedan en cada grupo?",
      ["Dividimos el total entre el número de grupos.",
       "156 ÷ 4 = 39."],
      "39 estudiantes", "39", "156/4"),
    R("div-08", "division", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 7.5 ÷ 2.5.",
      ["Multiplicamos ambos por 10: 75 ÷ 25.",
       "75 ÷ 25 = 3."],
      "3", "3", "7.5/2.5"),
    R("div-09", "division", "problema", "basico", "nuevo",
      "Se empacan 240 galletas en 16 paquetes iguales. ¿Cuántas galletas lleva cada paquete?",
      ["Dividimos el total entre el número de paquetes.",
       "240 ÷ 16 = 15."],
      "15 galletas", "15", "240/16"),
    R("div-10", "division", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 945 ÷ 7.",
      ["Dividimos los dos números.",
       "945 ÷ 7 = 135."],
      "135", "135", "945/7"),
    R("div-11", "division", "problema", "basico", "nuevo",
      "Una familia gastó 350000 pesos en 5 meses, la misma cantidad cada mes. ¿Cuánto gastó por mes?",
      ["Dividimos el gasto total entre el número de meses.",
       "350000 ÷ 5 = 70000."],
      "70000 pesos", "70000", "350000/5"),
    R("div-12", "division", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 100 ÷ 8.",
      ["Dividimos: 8 cabe 12 veces en 100 y sobran 4.",
       "El resultado exacto es 12.5."],
      "12.5", "12.5", "100/8"),
    R("div-13", "division", "problema", "intermedio", "nuevo",
      "Se quieren envasar 84 litros de jugo en botellas de 3.5 litros. ¿Cuántas botellas se llenan?",
      ["Dividimos el volumen total entre la capacidad de cada botella.",
       "84 ÷ 3.5 = 24."],
      "24 botellas", "24", "84/3.5"),
    R("div-14", "division", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 4860 ÷ 90.",
      ["Simplificamos quitando un cero en ambos: 486 ÷ 9.",
       "486 ÷ 9 = 54."],
      "54", "54", "4860/90"),
    R("div-15", "division", "problema", "intermedio", "nuevo",
      "Un profesor quiere formar equipos de 6 estudiantes con un curso de 53 estudiantes. ¿Cuántos equipos completos se forman?",
      ["Dividimos: 53 ÷ 6 = 8 con residuo 5.",
       "Solo cuentan los equipos completos, así que son 8 equipos y quedan 5 estudiantes sin equipo."],
      "8 equipos", "8", "53//6"),
]

# ------------------------------------------ operaciones_combinadas (15)
# Regla de etiquetado: dos o más operaciones distintas y/o paréntesis,
# sin potencias ni raíces (esas van a `potencias_raices`).
REGISTROS += [
    R("com-01", "operaciones_combinadas", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 125 + 87 - 39.",
      ["Resolvemos de izquierda a derecha: 125 + 87 = 212.",
       "Restamos: 212 - 39 = 173."],
      "173", "173", "125+87-39"),
    R("com-02", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 48 × 15 + 120.",
      ["La multiplicación tiene prioridad: 48 × 15 = 720.",
       "Sumamos: 720 + 120 = 840."],
      "840", "840", "48*15+120"),
    R("com-03", "operaciones_combinadas", "operacion", "basico", "base",
      "Resuelve la siguiente operación: (35 + 18) × 4.",
      ["Resolvemos primero el paréntesis: 35 + 18 = 53.",
       "Multiplicamos: 53 × 4 = 212."],
      "212", "212", "(35+18)*4"),
    R("com-04", "operaciones_combinadas", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 960 ÷ 8 - 25.",
      ["La división tiene prioridad: 960 ÷ 8 = 120.",
       "Restamos: 120 - 25 = 95."],
      "95", "95", "960/8-25"),
    R("com-05", "operaciones_combinadas", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 14 × (12 - 5).",
      ["Resolvemos primero el paréntesis: 12 - 5 = 7.",
       "Multiplicamos: 14 × 7 = 98."],
      "98", "98", "14*(12-5)"),
    R("com-06", "operaciones_combinadas", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 500 - 175 + 89.",
      ["Resolvemos de izquierda a derecha: 500 - 175 = 325.",
       "Sumamos: 325 + 89 = 414."],
      "414", "414", "500-175+89"),
    R("com-07", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: (2.8 + 1.7) × 3.",
      ["Resolvemos el paréntesis: 2.8 + 1.7 = 4.5.",
       "Multiplicamos: 4.5 × 3 = 13.5."],
      "13.5", "13.5", "(2.8+1.7)*3"),
    R("com-08", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 18 + 6 × 7 - 12.",
      ["La multiplicación va primero: 6 × 7 = 42.",
       "Resolvemos de izquierda a derecha: 18 + 42 = 60 y 60 - 12 = 48."],
      "48", "48", "18+6*7-12"),
    R("com-09", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: (45 - 9) ÷ 6 + 11.",
      ["Resolvemos el paréntesis: 45 - 9 = 36.",
       "Dividimos: 36 ÷ 6 = 6.",
       "Sumamos: 6 + 11 = 17."],
      "17", "17", "(45-9)/6+11"),
    R("com-10", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 3 × (8 + 5) - 14.",
      ["Resolvemos el paréntesis: 8 + 5 = 13.",
       "Multiplicamos: 3 × 13 = 39.",
       "Restamos: 39 - 14 = 25."],
      "25", "25", "3*(8+5)-14"),
    R("com-11", "operaciones_combinadas", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: (64 ÷ 8) × (15 - 7).",
      ["Resolvemos cada paréntesis: 64 ÷ 8 = 8 y 15 - 7 = 8.",
       "Multiplicamos: 8 × 8 = 64."],
      "64", "64", "(64/8)*(15-7)"),
    R("com-12", "operaciones_combinadas", "problema", "basico", "base",
      "Un autobús transporta 36 pasajeros. En la primera parada bajan 8 personas y suben 5. ¿Cuántos pasajeros quedan en el autobús?",
      ["Restamos los que bajan: 36 - 8 = 28.",
       "Sumamos los que suben: 28 + 5 = 33."],
      "33 pasajeros", "33", "36-8+5"),
    R("com-13", "operaciones_combinadas", "problema", "basico", "base",
      "Una caja contiene 24 lápices. Si se utilizan 9 lápices y luego se agregan 12 nuevos, ¿cuántos lápices hay ahora en la caja?",
      ["Restamos los lápices usados: 24 - 9 = 15.",
       "Sumamos los nuevos: 15 + 12 = 27."],
      "27 lápices", "27", "24-9+12"),
    R("com-14", "operaciones_combinadas", "problema", "intermedio", "nuevo",
      "En un mercado se compran 3 cuadernos de 4500 pesos cada uno y 2 libros de 6000 pesos cada uno. ¿Cuánto se pagó en total?",
      ["Cuadernos: 3 × 4500 = 13500.",
       "Libros: 2 × 6000 = 12000.",
       "Sumamos los dos gastos: 13500 + 12000 = 25500."],
      "25500 pesos", "25500", "3*4500+2*6000"),
    R("com-15", "operaciones_combinadas", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 72 ÷ (4 + 5) × 3.",
      ["Resolvemos el paréntesis: 4 + 5 = 9.",
       "Dividimos: 72 ÷ 9 = 8.",
       "Multiplicamos: 8 × 3 = 24."],
      "24", "24", "72/(4+5)*3"),
]

# ------------------------------------------------- potencias_raices (15)
REGISTROS += [
    R("pot-01", "potencias_raices", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 5² + 3².",
      ["Calculamos las potencias: 5² = 25 y 3² = 9.",
       "Sumamos: 25 + 9 = 34."],
      "34", "34", "5**2+3**2"),
    R("pot-02", "potencias_raices", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 2³ × 4.",
      ["Calculamos la potencia: 2³ = 8.",
       "Multiplicamos: 8 × 4 = 32."],
      "32", "32", "2**3*4"),
    R("pot-03", "potencias_raices", "operacion", "basico", "base",
      "Resuelve la siguiente operación: √144 + 8.",
      ["La raíz cuadrada de 144 es 12 porque 12 × 12 = 144.",
       "Sumamos: 12 + 8 = 20."],
      "20", "20", "144**0.5+8"),
    R("pot-04", "potencias_raices", "operacion", "basico", "base",
      "Resuelve la siguiente operación: √225 - √49.",
      ["Calculamos las raíces: √225 = 15 y √49 = 7.",
       "Restamos: 15 - 7 = 8."],
      "8", "8", "225**0.5-49**0.5"),
    R("pot-05", "potencias_raices", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: (9² - 25) ÷ 7 + 6.",
      ["Calculamos la potencia: 9² = 81.",
       "Resolvemos el paréntesis: 81 - 25 = 56.",
       "Dividimos y sumamos: 56 ÷ 7 = 8 y 8 + 6 = 14."],
      "14", "14", "(9**2-25)/7+6"),
    R("pot-06", "potencias_raices", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 4³.",
      ["Elevar al cubo es multiplicar el número tres veces: 4 × 4 × 4.",
       "4 × 4 = 16 y 16 × 4 = 64."],
      "64", "64", "4**3"),
    R("pot-07", "potencias_raices", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: √81 × 2.",
      ["La raíz cuadrada de 81 es 9.",
       "Multiplicamos: 9 × 2 = 18."],
      "18", "18", "81**0.5*2"),
    R("pot-08", "potencias_raices", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 10² - 6².",
      ["Calculamos las potencias: 10² = 100 y 6² = 36.",
       "Restamos: 100 - 36 = 64."],
      "64", "64", "10**2-6**2"),
    R("pot-09", "potencias_raices", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 3⁴.",
      ["Multiplicamos el 3 cuatro veces: 3 × 3 = 9 y 9 × 3 = 27.",
       "27 × 3 = 81."],
      "81", "81", "3**4"),
    R("pot-10", "potencias_raices", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: √169 + √36.",
      ["Calculamos las raíces: √169 = 13 y √36 = 6.",
       "Sumamos: 13 + 6 = 19."],
      "19", "19", "169**0.5+36**0.5"),
    R("pot-11", "potencias_raices", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 2⁵.",
      ["Multiplicamos el 2 cinco veces: 2 × 2 × 2 × 2 × 2.",
       "El resultado es 32."],
      "32", "32", "2**5"),
    R("pot-12", "potencias_raices", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: √100 + 5².",
      ["Calculamos la raíz: √100 = 10.",
       "Calculamos la potencia: 5² = 25.",
       "Sumamos: 10 + 25 = 35."],
      "35", "35", "100**0.5+5**2"),
    R("pot-13", "potencias_raices", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 6² ÷ 4.",
      ["Calculamos la potencia: 6² = 36.",
       "Dividimos: 36 ÷ 4 = 9."],
      "9", "9", "6**2/4"),
    R("pot-14", "potencias_raices", "problema", "basico", "nuevo",
      "¿Cuál es el resultado de elevar 12 al cuadrado?",
      ["Elevar al cuadrado es multiplicar el número por sí mismo.",
       "12 × 12 = 144."],
      "144", "144", "12**2"),
    R("pot-15", "potencias_raices", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: √400 ÷ 2.",
      ["La raíz cuadrada de 400 es 20.",
       "Dividimos: 20 ÷ 2 = 10."],
      "10", "10", "400**0.5/2"),
]

# ---------------------------------------------------------- fracciones (15)
REGISTROS += [
    R("fra-01", "fracciones", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 2/5 + 1/5.",
      ["Los denominadores son iguales, así que sumamos solo los numeradores.",
       "2 + 1 = 3, entonces el resultado es 3/5."],
      "3/5", "3/5", "2/5+1/5"),
    R("fra-02", "fracciones", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 3/4 - 1/8.",
      ["Convertimos 3/4 a octavos: 3/4 = 6/8.",
       "Restamos: 6/8 - 1/8 = 5/8."],
      "5/8", "5/8", "3/4-1/8"),
    R("fra-03", "fracciones", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 5/6 + 1/3.",
      ["Convertimos 1/3 a sextos: 1/3 = 2/6.",
       "Sumamos: 5/6 + 2/6 = 7/6."],
      "7/6", "7/6", "5/6+1/3"),
    R("fra-04", "fracciones", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 7/10 - 2/5.",
      ["Convertimos 2/5 a décimos: 2/5 = 4/10.",
       "Restamos: 7/10 - 4/10 = 3/10."],
      "3/10", "3/10", "7/10-2/5"),
    R("fra-05", "fracciones", "operacion", "basico", "base",
      "Resuelve la siguiente operación: 3/7 × 14.",
      ["Multiplicamos el numerador por el entero: 3 × 14 = 42.",
       "Dividimos entre el denominador: 42 ÷ 7 = 6."],
      "6", "6", "3/7*14"),
    R("fra-06", "fracciones", "operacion", "intermedio", "base",
      "Resuelve la siguiente operación: 4/9 ÷ 2/3.",
      ["Dividir por una fracción es multiplicar por su inversa: (4/9) × (3/2).",
       "Obtenemos 12/18, que simplificado es 2/3."],
      "2/3", "2/3", "4/9/(2/3)"),
    R("fra-07", "fracciones", "problema", "basico", "base",
      "Una pizza se divide en 8 porciones iguales. Si una familia consume 5 porciones, ¿qué fracción de la pizza queda sin consumir?",
      ["La pizza completa es 8/8 y se consumen 5/8.",
       "Restamos: 8/8 - 5/8 = 3/8."],
      "3/8 de la pizza", "3/8", "8/8-5/8"),
    R("fra-08", "fracciones", "problema", "intermedio", "base",
      "Un libro tiene 240 páginas y Ana ha leído 3/5 del libro. ¿Cuántas páginas ha leído?",
      ["Calculamos la fracción de la cantidad: (3/5) × 240.",
       "240 ÷ 5 = 48 y 48 × 3 = 144."],
      "144 páginas", "144", "3/5*240"),
    R("fra-09", "fracciones", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 1/2 + 1/3.",
      ["El denominador común de 2 y 3 es 6: 1/2 = 3/6 y 1/3 = 2/6.",
       "Sumamos: 3/6 + 2/6 = 5/6."],
      "5/6", "5/6", "1/2+1/3"),
    R("fra-10", "fracciones", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 2/3 × 3/4.",
      ["Multiplicamos numeradores y denominadores: (2 × 3)/(3 × 4) = 6/12.",
       "Simplificamos dividiendo entre 6: 6/12 = 1/2."],
      "1/2", "1/2", "2/3*3/4"),
    R("fra-11", "fracciones", "operacion", "intermedio", "nuevo",
      "Resuelve la siguiente operación: 5/8 ÷ 1/4.",
      ["Multiplicamos por la inversa: (5/8) × (4/1) = 20/8.",
       "Simplificamos dividiendo entre 4: 20/8 = 5/2."],
      "5/2", "5/2", "5/8/(1/4)"),
    R("fra-12", "fracciones", "problema", "basico", "nuevo",
      "En un curso de 60 estudiantes, 2/5 practican natación. ¿Cuántos estudiantes practican natación?",
      ["Calculamos la fracción de la cantidad: (2/5) × 60.",
       "60 ÷ 5 = 12 y 12 × 2 = 24."],
      "24 estudiantes", "24", "2/5*60"),
    R("fra-13", "fracciones", "operacion", "basico", "nuevo",
      "Simplifica la fracción 9/12.",
      ["El máximo común divisor de 9 y 12 es 3.",
       "Dividimos numerador y denominador entre 3: 9/12 = 3/4."],
      "3/4", "3/4", "9/12"),
    R("fra-14", "fracciones", "problema", "intermedio", "nuevo",
      "Una receta usa 3/4 de taza de azúcar. Si se prepara el doble de la receta, ¿cuánta azúcar se necesita?",
      ["Multiplicamos la cantidad por 2: (3/4) × 2 = 6/4.",
       "Simplificamos: 6/4 = 3/2, es decir, una taza y media."],
      "3/2 de taza", "3/2", "3/4*2"),
    R("fra-15", "fracciones", "operacion", "basico", "nuevo",
      "Resuelve la siguiente operación: 7/3 - 4/3.",
      ["Los denominadores son iguales, restamos los numeradores: 7 - 4 = 3.",
       "Obtenemos 3/3, que equivale a 1."],
      "1", "1", "7/3-4/3"),
]

# --------------------------------------------------------- porcentajes (15)
REGISTROS += [
    R("por-01", "porcentajes", "problema", "basico", "base",
      "En una escuela hay 420 estudiantes. Si el 25% participa en un torneo deportivo, ¿cuántos estudiantes participan?",
      ["El 25% equivale a multiplicar por 0.25.",
       "420 × 0.25 = 105."],
      "105 estudiantes", "105", "420*0.25"),
    R("por-02", "porcentajes", "problema", "intermedio", "base",
      "Un comerciante compró un producto por 80000 pesos y lo vendió por 96000 pesos. ¿Qué porcentaje de ganancia obtuvo?",
      ["Calculamos la ganancia: 96000 - 80000 = 16000.",
       "Dividimos la ganancia entre el costo: 16000 ÷ 80000 = 0.20.",
       "Convertimos a porcentaje: 0.20 × 100 = 20%."],
      "20%", "20", "(96000-80000)/80000*100"),
    R("por-03", "porcentajes", "problema", "basico", "base",
      "Una tienda ofrece un descuento del 20% sobre una camiseta que cuesta 75000 pesos. ¿Cuál es el precio final?",
      ["Calculamos el descuento: 75000 × 0.20 = 15000.",
       "Restamos el descuento al precio: 75000 - 15000 = 60000."],
      "60000 pesos", "60000", "75000*0.8"),
    R("por-04", "porcentajes", "problema", "basico", "base",
      "Un depósito contiene 180 litros de agua. Si se utiliza el 35% del agua, ¿cuántos litros quedan?",
      ["Calculamos el 35% de 180: 180 × 0.35 = 63.",
       "Restamos lo utilizado: 180 - 63 = 117."],
      "117 litros", "117", "180*0.65"),
    R("por-05", "porcentajes", "problema", "intermedio", "base",
      "En una encuesta a 40 estudiantes, 18 prefieren matemáticas. ¿Qué porcentaje de estudiantes prefiere matemáticas?",
      ["Dividimos la parte entre el total: 18 ÷ 40 = 0.45.",
       "Convertimos a porcentaje: 0.45 × 100 = 45%."],
      "45%", "45", "18/40*100"),
    R("por-06", "porcentajes", "operacion", "basico", "nuevo",
      "Calcula el 10% de 850.",
      ["El 10% equivale a dividir entre 10.",
       "850 ÷ 10 = 85."],
      "85", "85", "850*0.10"),
    R("por-07", "porcentajes", "operacion", "basico", "nuevo",
      "Calcula el 15% de 200.",
      ["El 15% equivale a multiplicar por 0.15.",
       "200 × 0.15 = 30."],
      "30", "30", "200*0.15"),
    R("por-08", "porcentajes", "problema", "intermedio", "nuevo",
      "Un producto cuesta 50000 pesos antes de impuestos y se le aplica un IVA del 19%. ¿Cuál es el precio final?",
      ["Calculamos el IVA: 50000 × 0.19 = 9500.",
       "Sumamos el IVA al precio: 50000 + 9500 = 59500."],
      "59500 pesos", "59500", "50000*1.19"),
    R("por-09", "porcentajes", "problema", "basico", "nuevo",
      "Un estudiante respondió correctamente 42 de 50 preguntas. ¿Qué porcentaje de aciertos obtuvo?",
      ["Dividimos los aciertos entre el total: 42 ÷ 50 = 0.84.",
       "Convertimos a porcentaje: 0.84 × 100 = 84%."],
      "84%", "84", "42/50*100"),
    R("por-10", "porcentajes", "operacion", "basico", "nuevo",
      "¿Qué porcentaje representa 18 de 60?",
      ["Dividimos: 18 ÷ 60 = 0.30.",
       "Convertimos a porcentaje: 0.30 × 100 = 30%."],
      "30%", "30", "18/60*100"),
    R("por-11", "porcentajes", "problema", "intermedio", "nuevo",
      "El salario de un empleado pasó de 40000 a 46000 pesos. ¿Cuál fue el porcentaje de aumento?",
      ["Calculamos el aumento: 46000 - 40000 = 6000.",
       "Dividimos entre el valor inicial: 6000 ÷ 40000 = 0.15.",
       "Convertimos a porcentaje: 0.15 × 100 = 15%."],
      "15%", "15", "(46000-40000)/40000*100"),
    R("por-12", "porcentajes", "operacion", "basico", "nuevo",
      "Calcula el 5% de 1200.",
      ["El 5% equivale a multiplicar por 0.05.",
       "1200 × 0.05 = 60."],
      "60", "60", "1200*0.05"),
    R("por-13", "porcentajes", "problema", "intermedio", "nuevo",
      "Un televisor cuesta 120000 pesos y tiene un descuento del 30%. ¿Cuánto se paga por él?",
      ["Calculamos el descuento: 120000 × 0.30 = 36000.",
       "Restamos el descuento: 120000 - 36000 = 84000."],
      "84000 pesos", "84000", "120000*0.7"),
    R("por-14", "porcentajes", "problema", "intermedio", "nuevo",
      "Un municipio tiene 25000 habitantes y su población aumenta un 8%. ¿Cuántos habitantes tendrá?",
      ["Calculamos el aumento: 25000 × 0.08 = 2000.",
       "Sumamos el aumento a la población: 25000 + 2000 = 27000."],
      "27000 habitantes", "27000", "25000*1.08"),
    R("por-15", "porcentajes", "operacion", "intermedio", "nuevo",
      "Calcula el 120% de 45.",
      ["El 120% equivale a multiplicar por 1.20.",
       "45 × 1.20 = 54."],
      "54", "54", "45*1.20"),
]

# ---------------------------------------------------------- ecuaciones (15)
REGISTROS += [
    R("ecu-01", "ecuaciones", "problema", "basico", "base",
      "La suma de un número y 15 es igual a 42. ¿Cuál es ese número?",
      ["Planteamos la ecuación: x + 15 = 42.",
       "Restamos 15 a ambos lados: x = 42 - 15 = 27."],
      "27", "27", "42-15"),
    R("ecu-02", "ecuaciones", "operacion", "basico", "nuevo",
      "Resuelve la ecuación: 3x = 27.",
      ["Dividimos ambos lados entre 3.",
       "x = 27 ÷ 3 = 9."],
      "x = 9", "9", "27/3"),
    R("ecu-03", "ecuaciones", "operacion", "basico", "nuevo",
      "Resuelve la ecuación: 2x + 5 = 19.",
      ["Restamos 5 a ambos lados: 2x = 14.",
       "Dividimos entre 2: x = 7."],
      "x = 7", "7", "(19-5)/2"),
    R("ecu-04", "ecuaciones", "operacion", "basico", "nuevo",
      "Resuelve la ecuación: x / 4 = 12.",
      ["Multiplicamos ambos lados por 4.",
       "x = 12 × 4 = 48."],
      "x = 48", "48", "12*4"),
    R("ecu-05", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve la ecuación: 5x - 8 = 32.",
      ["Sumamos 8 a ambos lados: 5x = 40.",
       "Dividimos entre 5: x = 8."],
      "x = 8", "8", "(32+8)/5"),
    R("ecu-06", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve la ecuación: 4(x - 2) = 20.",
      ["Dividimos ambos lados entre 4: x - 2 = 5.",
       "Sumamos 2: x = 7."],
      "x = 7", "7", "20/4+2"),
    R("ecu-07", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve la ecuación: 7x + 3 = 3x + 19.",
      ["Agrupamos las x a la izquierda: 7x - 3x = 19 - 3.",
       "Obtenemos 4x = 16, por lo tanto x = 4."],
      "x = 4", "4", "(19-3)/(7-3)"),
    R("ecu-08", "ecuaciones", "problema", "intermedio", "nuevo",
      "El doble de un número menos 6 es igual a 18. ¿Cuál es el número?",
      ["Planteamos la ecuación: 2x - 6 = 18.",
       "Sumamos 6: 2x = 24.",
       "Dividimos entre 2: x = 12."],
      "12", "12", "(18+6)/2"),
    R("ecu-09", "ecuaciones", "problema", "intermedio", "nuevo",
      "Luis tiene 5 años más que Ana y entre los dos suman 31 años. ¿Cuántos años tiene Ana?",
      ["Si Ana tiene x años, Luis tiene x + 5.",
       "Planteamos: x + (x + 5) = 31, es decir 2x + 5 = 31.",
       "Restamos 5 y dividimos entre 2: 2x = 26 y x = 13."],
      "13 años", "13", "(31-5)/2"),
    R("ecu-10", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve la ecuación: x / 3 + 2 = 7.",
      ["Restamos 2 a ambos lados: x / 3 = 5.",
       "Multiplicamos por 3: x = 15."],
      "x = 15", "15", "(7-2)*3"),
    R("ecu-11", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve el sistema x + y = 10 y x - y = 4. ¿Cuál es el valor de x?",
      ["Sumamos las dos ecuaciones para eliminar y: 2x = 14.",
       "Dividimos entre 2: x = 7 (y en consecuencia y = 3)."],
      "x = 7", "7", "(10+4)/2"),
    R("ecu-12", "ecuaciones", "operacion", "intermedio", "nuevo",
      "Resuelve el sistema 2x + y = 13 y y = x + 1. ¿Cuál es el valor de x?",
      ["Sustituimos y en la primera ecuación: 2x + (x + 1) = 13.",
       "Agrupamos: 3x + 1 = 13, entonces 3x = 12.",
       "Dividimos entre 3: x = 4 (y en consecuencia y = 5)."],
      "x = 4", "4", "(13-1)/3"),
    R("ecu-13", "ecuaciones", "operacion", "basico", "nuevo",
      "Resuelve la ecuación: 6x = 4x + 14.",
      ["Restamos 4x a ambos lados: 2x = 14.",
       "Dividimos entre 2: x = 7."],
      "x = 7", "7", "14/2"),
    R("ecu-14", "ecuaciones", "problema", "basico", "nuevo",
      "Tres camisas iguales cuestan 96000 pesos en total. ¿Cuánto cuesta cada camisa?",
      ["Si cada camisa cuesta x, planteamos 3x = 96000.",
       "Dividimos entre 3: x = 32000."],
      "32000 pesos", "32000", "96000/3"),
    R("ecu-15", "ecuaciones", "operacion", "basico", "nuevo",
      "Resuelve la ecuación: 9 - x = 2.",
      ["Pasamos x al otro lado y 2 al primero: 9 - 2 = x.",
       "x = 7."],
      "x = 7", "7", "9-2"),
]

# ----------------------------------------------------------- geometria (15)
REGISTROS += [
    R("geo-01", "geometria", "problema", "basico", "base",
      "Un terreno rectangular mide 12 metros de largo y 8 metros de ancho. ¿Cuál es su área?",
      ["El área de un rectángulo es largo × ancho.",
       "12 × 8 = 96."],
      "96 metros cuadrados", "96", "12*8"),
    R("geo-02", "geometria", "problema", "basico", "base",
      "Un terreno rectangular mide 12 metros de largo y 8 metros de ancho. ¿Cuál es su perímetro?",
      ["El perímetro de un rectángulo es 2 × (largo + ancho).",
       "2 × (12 + 8) = 2 × 20 = 40."],
      "40 metros", "40", "2*(12+8)"),
    R("geo-03", "geometria", "problema", "intermedio", "base",
      "En un triángulo, dos ángulos miden 48 grados y 67 grados. ¿Cuánto mide el tercer ángulo?",
      ["Los ángulos interiores de un triángulo suman 180 grados.",
       "180 - (48 + 67) = 180 - 115 = 65."],
      "65 grados", "65", "180-(48+67)"),
    R("geo-04", "geometria", "problema", "basico", "nuevo",
      "Un triángulo tiene una base de 10 centímetros y una altura de 6 centímetros. ¿Cuál es su área?",
      ["El área de un triángulo es (base × altura) ÷ 2.",
       "(10 × 6) ÷ 2 = 60 ÷ 2 = 30."],
      "30 centímetros cuadrados", "30", "10*6/2"),
    R("geo-05", "geometria", "problema", "basico", "nuevo",
      "¿Cuál es el perímetro de un cuadrado cuyo lado mide 9 centímetros?",
      ["El perímetro de un cuadrado es 4 × lado.",
       "4 × 9 = 36."],
      "36 centímetros", "36", "4*9"),
    R("geo-06", "geometria", "problema", "intermedio", "nuevo",
      "Calcula el área de un círculo de radio 5 centímetros usando π = 3.14.",
      ["El área de un círculo es π × radio².",
       "3.14 × 5² = 3.14 × 25 = 78.5."],
      "78.5 centímetros cuadrados", "78.5", "3.14*5**2"),
    R("geo-07", "geometria", "problema", "intermedio", "nuevo",
      "Calcula la longitud de una circunferencia de radio 7 centímetros usando π = 3.14.",
      ["La longitud de la circunferencia es 2 × π × radio.",
       "2 × 3.14 × 7 = 43.96."],
      "43.96 centímetros", "43.96", "2*3.14*7"),
    R("geo-08", "geometria", "problema", "basico", "nuevo",
      "¿Cuál es el área de un cuadrado cuyo lado mide 12 metros?",
      ["El área de un cuadrado es lado × lado.",
       "12 × 12 = 144."],
      "144 metros cuadrados", "144", "12*12"),
    R("geo-09", "geometria", "problema", "basico", "nuevo",
      "Un patio rectangular mide 15 metros por 7 metros. ¿Cuántos metros cuadrados tiene?",
      ["El área de un rectángulo es largo × ancho.",
       "15 × 7 = 105."],
      "105 metros cuadrados", "105", "15*7"),
    R("geo-10", "geometria", "problema", "intermedio", "nuevo",
      "¿Cuál es el volumen de un cubo cuya arista mide 4 centímetros?",
      ["El volumen de un cubo es arista³.",
       "4 × 4 × 4 = 64."],
      "64 centímetros cúbicos", "64", "4**3"),
    R("geo-11", "geometria", "problema", "intermedio", "nuevo",
      "Dos ángulos son suplementarios y uno de ellos mide 115 grados. ¿Cuánto mide el otro?",
      ["Dos ángulos suplementarios suman 180 grados.",
       "180 - 115 = 65."],
      "65 grados", "65", "180-115"),
    R("geo-12", "geometria", "problema", "intermedio", "nuevo",
      "Un trapecio tiene bases de 10 y 6 centímetros y una altura de 4 centímetros. ¿Cuál es su área?",
      ["El área de un trapecio es ((base mayor + base menor) ÷ 2) × altura.",
       "((10 + 6) ÷ 2) × 4 = 8 × 4 = 32."],
      "32 centímetros cuadrados", "32", "(10+6)/2*4"),
    R("geo-13", "geometria", "problema", "basico", "nuevo",
      "Se quiere cercar un terreno rectangular de 20 metros de largo por 14 metros de ancho. ¿Cuántos metros de cerca se necesitan?",
      ["La cerca corresponde al perímetro: 2 × (largo + ancho).",
       "2 × (20 + 14) = 2 × 34 = 68."],
      "68 metros", "68", "2*(20+14)"),
    R("geo-14", "geometria", "problema", "intermedio", "nuevo",
      "Un triángulo rectángulo tiene catetos de 3 y 4 centímetros. ¿Cuánto mide la hipotenusa?",
      ["Por el teorema de Pitágoras: hipotenusa² = 3² + 4² = 9 + 16 = 25.",
       "La hipotenusa es √25 = 5."],
      "5 centímetros", "5", "(3**2+4**2)**0.5"),
    R("geo-15", "geometria", "problema", "basico", "nuevo",
      "Una caja mide 5 centímetros de largo, 3 de ancho y 2 de alto. ¿Cuál es su volumen?",
      ["El volumen de un prisma rectangular es largo × ancho × alto.",
       "5 × 3 × 2 = 30."],
      "30 centímetros cúbicos", "30", "5*3*2"),
]

# ------------------------------------------ estadistica_probabilidad (15)
REGISTROS += [
    R("est-01", "estadistica_probabilidad", "problema", "intermedio", "base",
      "Un estudiante obtuvo las siguientes calificaciones: 4.2, 3.8, 4.5 y 4.0. ¿Cuál es el promedio de sus calificaciones?",
      ["Sumamos las notas: 4.2 + 3.8 + 4.5 + 4.0 = 16.5.",
       "Dividimos entre la cantidad de notas: 16.5 ÷ 4 = 4.125."],
      "4.125", "4.125", "(4.2+3.8+4.5+4.0)/4"),
    R("est-02", "estadistica_probabilidad", "problema", "basico", "base",
      "Una bolsa contiene 5 bolas rojas, 3 azules y 2 verdes. Si se extrae una bola al azar, ¿cuál es la probabilidad de que sea azul?",
      ["Contamos el total de bolas: 5 + 3 + 2 = 10.",
       "La probabilidad es casos favorables sobre casos posibles: 3/10."],
      "3/10", "3/10", "3/10"),
    R("est-03", "estadistica_probabilidad", "operacion", "basico", "nuevo",
      "Calcula el promedio de los números 12, 18 y 24.",
      ["Sumamos los valores: 12 + 18 + 24 = 54.",
       "Dividimos entre la cantidad de valores: 54 ÷ 3 = 18."],
      "18", "18", "(12+18+24)/3"),
    R("est-04", "estadistica_probabilidad", "operacion", "basico", "nuevo",
      "¿Cuál es la moda del conjunto 3, 5, 5, 7 y 9?",
      ["La moda es el valor que más se repite.",
       "El 5 aparece dos veces y los demás una sola vez, así que la moda es 5."],
      "5", "5", "5"),
    R("est-05", "estadistica_probabilidad", "operacion", "intermedio", "nuevo",
      "¿Cuál es la mediana del conjunto 4, 8, 15, 16 y 23?",
      ["Los datos ya están ordenados y son 5 valores.",
       "La mediana es el valor central, es decir, el tercero: 15."],
      "15", "15", "15"),
    R("est-06", "estadistica_probabilidad", "problema", "basico", "nuevo",
      "Al lanzar un dado de seis caras, ¿cuál es la probabilidad de obtener un 4?",
      ["Hay 6 resultados posibles y solo uno es favorable.",
       "La probabilidad es 1/6."],
      "1/6", "1/6", "1/6"),
    R("est-07", "estadistica_probabilidad", "problema", "basico", "nuevo",
      "Al lanzar una moneda, ¿cuál es la probabilidad de que salga cara?",
      ["Hay 2 resultados posibles: cara o sello.",
       "Solo uno es favorable, así que la probabilidad es 1/2."],
      "1/2", "1/2", "1/2"),
    R("est-08", "estadistica_probabilidad", "problema", "intermedio", "nuevo",
      "Una caja tiene 20 fichas y 8 son rojas. Si se saca una ficha al azar, ¿cuál es la probabilidad de que sea roja?",
      ["La probabilidad es casos favorables sobre casos posibles: 8/20.",
       "Simplificamos dividiendo entre 4: 8/20 = 2/5."],
      "2/5", "2/5", "8/20"),
    R("est-09", "estadistica_probabilidad", "operacion", "basico", "nuevo",
      "Calcula el promedio de las notas 3.0, 4.0 y 5.0.",
      ["Sumamos las notas: 3.0 + 4.0 + 5.0 = 12.0.",
       "Dividimos entre 3: 12.0 ÷ 3 = 4.0."],
      "4", "4", "(3.0+4.0+5.0)/3"),
    R("est-10", "estadistica_probabilidad", "operacion", "basico", "nuevo",
      "¿Cuál es el rango del conjunto 12, 7, 20 y 5?",
      ["El rango es el valor mayor menos el valor menor.",
       "20 - 5 = 15."],
      "15", "15", "20-5"),
    R("est-11", "estadistica_probabilidad", "problema", "intermedio", "nuevo",
      "Se tienen 10 tarjetas numeradas del 1 al 10. Si se saca una al azar, ¿cuál es la probabilidad de que el número sea par?",
      ["Los números pares del 1 al 10 son 2, 4, 6, 8 y 10: son 5 casos favorables.",
       "La probabilidad es 5/10, que simplificada es 1/2."],
      "1/2", "1/2", "5/10"),
    R("est-12", "estadistica_probabilidad", "operacion", "intermedio", "nuevo",
      "¿Cuál es la mediana del conjunto 2, 4, 6 y 8?",
      ["Son 4 valores, así que la mediana es el promedio de los dos centrales.",
       "(4 + 6) ÷ 2 = 5."],
      "5", "5", "(4+6)/2"),
    R("est-13", "estadistica_probabilidad", "problema", "basico", "nuevo",
      "Un equipo anotó 2, 3, 1, 4 y 0 goles en sus últimos cinco partidos. ¿Cuál fue el promedio de goles por partido?",
      ["Sumamos los goles: 2 + 3 + 1 + 4 + 0 = 10.",
       "Dividimos entre 5 partidos: 10 ÷ 5 = 2."],
      "2 goles", "2", "(2+3+1+4+0)/5"),
    R("est-14", "estadistica_probabilidad", "problema", "intermedio", "nuevo",
      "Al lanzar un dado de seis caras, ¿cuál es la probabilidad de NO obtener un 6?",
      ["De los 6 resultados posibles, 5 no son el 6.",
       "La probabilidad es 5/6."],
      "5/6", "5/6", "5/6"),
    R("est-15", "estadistica_probabilidad", "problema", "basico", "nuevo",
      "En una encuesta a 25 personas, 15 prefieren el fútbol. Si se elige una persona al azar, ¿cuál es la probabilidad de que prefiera el fútbol?",
      ["La probabilidad es casos favorables sobre el total: 15/25.",
       "Simplificamos dividiendo entre 5: 15/25 = 3/5."],
      "3/5", "3/5", "15/25"),
]


